### ISSUE TITLE
Add SubSystems 

### ISSUE THREAD

**Issue by sdseifert** [RedHotChiliBots/CODE_2024_Crescendo#3]
Add empty SubSystems for 
Intake, Hopper, Shooter, Climber, Trapper.

Add Starting and Finishing comment to Constructor following this example.
    System.out.println("+++++ Starting Chassis Constructor +++++");
    System.out.println("----- Ending Chassis Constructor -----");

Add ShuffleBoard tab following this example, changing to reflect SubSystem name.
  private final ShuffleboardTab chassisTab = Shuffleboard.getTab("Chassis");

The following is an example of data placed on the tab.
  private final GenericEntry sbAngle = chassisTab.addPersistent("Angle", 0)
      .withWidget("Text View").withPosition(5, 0).withSize(2, 1).getEntry();

The following is an example of updating the data in the periodic() method.
    sbAngle.setDouble(getAngle().getDegrees());

**Comment by Kibbecode** [comment]
Added empty SubSystems for Intake, Hopper, Shooter, Climber, Trapper.

Added Starting and Finishing comment to Constructor

Added ShuffleBoard tab following this example, changing to reflect SubSystem name.
private final ShuffleboardTab chassisTab = Shuffleboard.getTab("Chassis");

have not used 
+++++++++++++++++++++++++++
The following is an example of data placed on the tab.
private final GenericEntry sbAngle = chassisTab.addPersistent("Angle", 0)
.withWidget("Text View").withPosition(5, 0).withSize(2, 1).getEntry();

The following is an example of updating the data in the periodic() method.
sbAngle.setDouble(getAngle().getDegrees());
